# 1. Cấu hình cổng chạy Server (Mặc định 8080)
server.port=8080

# 2. Kết nối Database MySQL (Tạo sẵn 1 database tên là 'webtruyen' trống trong localhost nha)
spring.datasource.url=jdbc:mysql://localhost:3306/webtruyen?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Cấu hình bùa chú JPA & Hibernate
# 'update': Tự động tạo bảng, thêm cột mới nếu code Java thay đổi, không làm mất data cũ
spring.jpa.hibernate.ddl-auto=update

# Bật cái này lên để xem console nó in ra câu lệnh SQL (rất tiện để debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect